name: Lint Dockerfile

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Lint Dockerfile
      uses: hadolint/hadolint-action@v2
      with:
        dockerfile: Dockerfile