name: Lint Dockerfile

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: Dockerfile